In [1]:
import numpy as np
import random
import math
#Bai 1
_a = [5, 7, 14]
a = np.array(_a)
print(a)
#Bai 2
_b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
b = np.array(_b)
print(b)
#Bai 3
n = int(input('Nhap so chieu:'))
_c =[]
for i in range(0,n):
    x = random.randint(0,20)
    _c.append(x)
c = np.array(_c)
print(c)





[ 5  7 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  5  2  3 17]


In [2]:
#Bai 4
oa = [7,-5, 8]
s = 0
for i in range(0, len(oa)):
    vb = pow(oa[i],2)
    s = s + vb
print(s)
s = math.sqrt(s)
print('Do dai vector OA:', s)
#Bai 5
n1 = int(input('Nhap so chieu:'))
a1 =[]
for i in range(0,n1):
    x = random.randint(0,20)
    a1.append(x)
a = np.array(a1)
b1 =[]
for i in range(0,n1):
    x = random.randint(0,20)
    b1.append(x)  
b = np.array(b1) 
c1 = []
for i in range(0,n1):
    x = b1[i]-a1[i]
    c1.append(x)
c = np.array(c1)

print('Diem A:',a,'Diem B:',b,'Vecto AB:',c)

s = 0
for i in range(0, len(c1)):
    vb = pow(c1[i],2)
    s = s + vb
s = math.sqrt(s)
print('Do dai vector AB:', s)




138
Do dai vector OA: 11.74734012447073
Diem A: [ 5  0  2 17] Diem B: [19  2 18  1] Vecto AB: [ 14   2  16 -16]
Do dai vector AB: 26.68332812825267


In [4]:
#Bai6
n1 = int(input('Nhap so chieu:'))
a1 =[]
for i in range(0,n1):
    x = random.randint(0,20)
    a1.append(x)
a = np.array(a1)
b1 =[]
for i in range(0,n1):
    x = random.randint(0,20)
    b1.append(x)  
b = np.array(b1)
print('Vecto a:',a, 'Vecto b:', b, 'Tich vo huong:',np.inner(a,b))
#Bai7
c = np.cross(a,b, axisa = -1, axisb = -1)
print('Tich co huong:',c)


Vecto a: [10 11  5] Vecto b: [10  3 14] Tich vo huong: 203
Tich co huong: [139 -90 -80]


In [8]:
#Bai8
n1 = int(input('Nhap so chieu:'))
a1 =[]
for i in range(0,n1):
    x = random.randint(0,20)
    a1.append(x)
a = np.array(a1)
print('Vecto a:',a1, 'Chuyen vi:',np.transpose(a))


In [3]:
#Bai9
a = [1,2,3,4,5]
b = [[1],[2],[3],[4],[5]]
print(a,b)
va = np.array(a)
vb = np.array(b)
print(va,vb)
trana = np.transpose(a)
tranb = np.transpose(b)
print(trana, tranb)


[1, 2, 3, 4, 5] [[1], [2], [3], [4], [5]]
[1 2 3 4 5] [[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5] [[1 2 3 4 5]]


In [9]:
#Bai 10
n = int(input('Nhap so chieu:'))
a1 =[]
for i in range(0,n):
    x = random.randint(0,20)
    a1.append(x)
a = np.array(a1)
print('a:',a)
m = random.randint(0,20)
k1=[]
for i in range(0, len(a1)):
    x = m*a1[i]
    k1.append(x)
k = np.array(k1)
print('m:',m)
print('m*a:',k)
b1 =[]
for i in range(0,n):
    x = random.randint(0,20)
    b1.append(x)
b = np.array(b1)
print('b:',b)
s1 = []
for i in range(0,len(a1)):
    x = a1[i]+b1[i]
    s1.append(x)

s = np.array(s1)

print('a+b:',s)




a: [5 7 4]
m: 7
m*a: [35 49 28]
b: [13  3  4]
a+b: [18 10  8]
