In [70]:
import numpy as np
from numpy.linalg import inv
#Bai1
print('1:',np.random.rand(7,5))
#Bai2
print('2:',np.zeros((6,7)))
#Bai3
print('3:',np.random.rand(7,7))
#bai4
a = np.zeros((6,6), int)
np.fill_diagonal(a, 15)
print('4:',a)


1: [[0.03136407 0.31039536 0.1748858  0.05650907 0.99751932]
 [0.09080398 0.34040155 0.41494217 0.53985823 0.81973481]
 [0.15114279 0.69885969 0.1520529  0.0541321  0.05709285]
 [0.02007377 0.29697068 0.59664667 0.10343329 0.43795736]
 [0.10670226 0.46413156 0.83291877 0.16286153 0.16343038]
 [0.41819624 0.35697376 0.08238485 0.68667633 0.89593803]
 [0.878424   0.8010787  0.00193128 0.5547134  0.18362475]]
2: [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
3: [[4.62416198e-01 7.67311231e-01 5.61144408e-01 9.04787732e-01
  9.76039022e-01 5.43252631e-01 4.84069212e-01]
 [9.64100065e-01 4.41669065e-01 5.56771248e-01 7.77328574e-01
  9.17480890e-02 8.98292039e-01 9.65141916e-01]
 [5.84376421e-01 4.79635466e-01 8.00993273e-01 3.22249881e-01
  8.95427642e-01 5.51585256e-01 7.24151781e-01]
 [3.69695905e-01 7.27704021e-01 2.00657072e-01 6.65700304e-01
  1.39771489e-01 5.75832789e-01 3.43258559e-01]

In [45]:
#bai5
b = np.random.rand(8,8)
b = np.matrix(b)
b_up = np.tril(b)
print('5:', b_up)

5: [[0.61765902 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.91290878 0.06592085 0.         0.         0.         0.
  0.         0.        ]
 [0.16799558 0.79743191 0.71365068 0.         0.         0.
  0.         0.        ]
 [0.19764485 0.43710788 0.53191642 0.07270021 0.         0.
  0.         0.        ]
 [0.22595093 0.2905375  0.21261712 0.31788076 0.60954597 0.
  0.         0.        ]
 [0.63538177 0.37724415 0.44215421 0.00643717 0.06616368 0.40378771
  0.         0.        ]
 [0.3606925  0.86745537 0.63208184 0.76591224 0.10766479 0.29735839
  0.48417733 0.        ]
 [0.71672141 0.97603215 0.3779369  0.33355448 0.11266965 0.78693501
  0.02940323 0.87531912]]


In [47]:
#Bai6
b = np.random.rand(8,8)
b = np.matrix(b)
b_under = np.triu(b)
print('5:', b_under)

5: [[0.15692479 0.60340998 0.71614924 0.26752999 0.4582406  0.31134451
  0.71960268 0.22031836]
 [0.         0.41733791 0.50331134 0.79120936 0.8354566  0.68749683
  0.28696905 0.66336756]
 [0.         0.         0.9773957  0.17493753 0.93759005 0.69376183
  0.80575939 0.66362936]
 [0.         0.         0.         0.71478904 0.28358393 0.14208255
  0.15824956 0.54164892]
 [0.         0.         0.         0.         0.19335514 0.25833544
  0.4631256  0.76212634]
 [0.         0.         0.         0.         0.         0.52354126
  0.78253419 0.65306464]
 [0.         0.         0.         0.         0.         0.
  0.14180892 0.80862348]
 [0.         0.         0.         0.         0.         0.
  0.         0.66256679]]


In [62]:
#bai7
np.identity(9)
#bai8a
a = np.matrix(np.random.rand(6,7))
b = np.matrix(np.random.rand(6,7))
c = a + b
print('a:',a,'b:',b,'c:',c)
#bai8b
a = np.matrix(np.random.rand(5,8))
m = int(input('Nhap m'))
b =m*a
print('a:',a,'b:',b)

a: [[0.18389    0.97406832 0.56020786 0.84826481 0.91021206 0.98488281
  0.53572219]
 [0.97407785 0.50919647 0.7400553  0.01854415 0.40693689 0.25111681
  0.66485246]
 [0.30646054 0.37118295 0.59876674 0.20970658 0.36440867 0.67262294
  0.82319666]
 [0.44712624 0.68009263 0.47237412 0.30746214 0.81088287 0.4075051
  0.51860538]
 [0.97399656 0.26123965 0.71744873 0.42806623 0.17362408 0.42623489
  0.88629734]
 [0.12905714 0.3931027  0.0184685  0.43291305 0.12034805 0.39742964
  0.31641284]] b: [[0.77664723 0.26359846 0.1856616  0.87469037 0.32708007 0.37703929
  0.70629979]
 [0.40449402 0.17970658 0.59981475 0.53871441 0.27378058 0.9370697
  0.12135851]
 [0.03488007 0.91315413 0.06507108 0.65515022 0.87384566 0.17612808
  0.95052301]
 [0.64807893 0.86160706 0.3552888  0.97070067 0.04641052 0.38620963
  0.45697574]
 [0.08571869 0.53851142 0.37233179 0.52894602 0.3646516  0.55700634
  0.10054109]
 [0.02740908 0.84020635 0.11567666 0.7284432  0.16546483 0.29191531
  0.85999472]] c: [[0.960

In [66]:
#bai8c
a = np.matrix(np.random.rand(7,3))
a_t = np.transpose(a)
print(a,a_t)
#bai8d
a = np.matrix(np.random.rand(5,7))
b = np.matrix(np.random.rand(7,3))
c = a.dot(b)
print('a:',a,'b:',b,'c:',c)

[[0.95681185 0.50966281 0.84722634]
 [0.978695   0.81311301 0.82266218]
 [0.53052424 0.4152865  0.25257776]
 [0.07304953 0.82410497 0.22003419]
 [0.02723683 0.22796684 0.77978872]
 [0.37398157 0.66717803 0.32425872]
 [0.46227595 0.83634682 0.85329424]] [[0.95681185 0.978695   0.53052424 0.07304953 0.02723683 0.37398157
  0.46227595]
 [0.50966281 0.81311301 0.4152865  0.82410497 0.22796684 0.66717803
  0.83634682]
 [0.84722634 0.82266218 0.25257776 0.22003419 0.77978872 0.32425872
  0.85329424]]
a: [[0.63255846 0.84428419 0.5742854  0.2160266  0.14672256 0.44040376
  0.02064659]
 [0.77175875 0.23390003 0.90633494 0.24731044 0.84301481 0.08327405
  0.1460255 ]
 [0.07192011 0.38889345 0.30994597 0.17049413 0.27050275 0.07771112
  0.36429481]
 [0.64294803 0.58945677 0.83032328 0.05552194 0.25819237 0.06218503
  0.80342652]
 [0.70796709 0.84443067 0.49224301 0.94921716 0.25685385 0.13434714
  0.67760919]] b: [[0.10311345 0.03919927 0.28286634]
 [0.08116218 0.47564204 0.60090309]
 [0.3413520

In [93]:
#bai8e
a = np.matrix(np.random.rand(5,7))
a_inv = np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [88]:
#bai9
print('row',np.random.rand(1,8))
print('column',np.random.rand(8,1))

row [[0.6530918  0.04959742 0.13002721 0.04838765 0.10110845 0.44674388
  0.30052829 0.93529488]]
column [[0.70459874]
 [0.18291569]
 [0.43906144]
 [0.48429128]
 [0.87797431]
 [0.37197873]
 [0.10548167]
 [0.637102  ]]


In [96]:
#bai10
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print('Heso pt:',A, 'he so tu do:',y)
print('Nghiem:',x)

Heso pt: [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]] he so tu do: [ 2  5 -3]
Nghiem: [ 2.20833333 -2.58333333 -0.18333333]
