In [1]:
import numpy as np
import pandas as pd
import random
from collections import Counter
#bai1
#
a = np.arange(1, 8, 1, dtype=int)
print(a)
print('So chieu:',a.ndim)
_a=np.transpose(a)
print('Kich thuoc:',a.shape, _a.shape)
#
a = np.linspace(2.0,3.0,num = 7)
print(a)
print('So chieu:',a.ndim)
_a=np.transpose(a)
print('Kich thuoc:',a.shape, _a.shape)
#
a = np.logspace(2.0,3.0,num=7)
print(a)
print('So chieu:',a.ndim)
_a=np.transpose(a)
print('Kich thuoc:',a.shape, _a.shape)
#
a = np.random.rand(1,7)
print(a)
print('So chieu:',a.ndim)
_a=np.transpose(a)
print('Kich thuoc:',a.shape, _a.shape)



[1 2 3 4 5 6 7]
So chieu: 1
Kich thuoc: (7,) (7,)
[2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.        ]
So chieu: 1
Kich thuoc: (7,) (7,)
[ 100.          146.77992676  215.443469    316.22776602  464.15888336
  681.29206906 1000.        ]
So chieu: 1
Kich thuoc: (7,) (7,)
[[0.27081144 0.10638083 0.56491466 0.75465859 0.85362677 0.09984383
  0.38344906]]
So chieu: 2
Kich thuoc: (1, 7) (7, 1)


In [50]:
#bai2
#
b1=[]
for i in range(0,10):
    x = np.arange(1,8,1, dtype = int)
    b1.append(x)
b1
b1 = np.matrix(b1)
_b1=np.transpose(b1)
print(_b1.shape)
print(_b1.ndim)
#
b=[]
for i in range(0,10):
    x = np.linspace(0.0,1.0,num = 7)
    b.append(x)
print(b)
b = np.matrix(b)
_b=np.transpose(b)
print(_b.shape)
print(_b.ndim)
#
b=[]
for i in range(0,10):
    x = np.logspace(0.0,1.0,num = 7)
    b.append(x)
print(b)
b = np.matrix(b)
_b=np.transpose(b)
print(_b.shape)
print(_b.ndim)
#
b=[]
for i in range(0,10):
    x = np.random.rand(1,7)
    x = np.array(x)
    b.append(x)
print(b)




(7, 10)
2
[array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ]), array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1. 

In [54]:
#
flat = b1.flatten()
print(flat)
re = np.reshape(flat, (7,10))
print(re)




[[1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1
  2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7]]
[[1 2 3 4 5 6 7 1 2 3]
 [4 5 6 7 1 2 3 4 5 6]
 [7 1 2 3 4 5 6 7 1 2]
 [3 4 5 6 7 1 2 3 4 5]
 [6 7 1 2 3 4 5 6 7 1]
 [2 3 4 5 6 7 1 2 3 4]
 [5 6 7 1 2 3 4 5 6 7]]


In [57]:
#
v = []
for i in range(0,10):
    x = np.logspace(0.0,1.0,num = 15)
    v.append(x)
mat = np.matrix(v)
print(mat)
mat.shape
print('Dong 3:', mat[2])
print('Cot 5:', mat[:,4])


    

[[ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584593
   2.6826958   3.16227766  3.72759372  4.39397056  5.17947468  6.1054023
   7.19685673  8.48342898 10.        ]
 [ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584593
   2.6826958   3.16227766  3.72759372  4.39397056  5.17947468  6.1054023
   7.19685673  8.48342898 10.        ]
 [ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584593
   2.6826958   3.16227766  3.72759372  4.39397056  5.17947468  6.1054023
   7.19685673  8.48342898 10.        ]
 [ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584593
   2.6826958   3.16227766  3.72759372  4.39397056  5.17947468  6.1054023
   7.19685673  8.48342898 10.        ]
 [ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584593
   2.6826958   3.16227766  3.72759372  4.39397056  5.17947468  6.1054023
   7.19685673  8.48342898 10.        ]
 [ 1.          1.17876863  1.38949549  1.63789371  1.93069773  2.27584

In [22]:
def tinh_mean(sample):
    return sum(sample) / len(sample)

def tinh_median(sample):
    n = len(sample)
    index = n // 2
    if n % 2:
        return sorted(sample)[index]
    return sum(sorted(sample)[index - 1:index + 1]) / 2

def tinh_mode(sample):
    c = Counter(sample)
    return [k for k, v in c.items() if v == c.most_common(1)[0][1]]

t = []
for i in range(0,15):
    x = np.arange(1,11,1, dtype=int)
    t.append(x)
mat = np.matrix(t)
mat.shape

mean = np.apply_along_axis(tinh_mean,0,mat)
median = np.apply_along_axis(tinh_median,0,mat)
mode = np.apply_along_axis(tinh_mode,0,mat)


TypeError: unhashable type: 'matrix'